/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 15 23:36:44 EST 2017
 */

package main;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = false, useJEE = true) 
public class Util_ESTest extends Util_ESTest_scaffolding {

  @Test(timeout = 100000)
  public void test0()  throws Throwable  {
      double double0 = Util.round(0.0, 1);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 100000)
  public void test1()  throws Throwable  {
      double double0 = Util.round(0.9547051850585937, 0);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 100000)
  public void test2()  throws Throwable  {
      double double0 = Util.round((-0.5600635755864344), 0);
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 100000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        Util.round(0.0, (-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Util", e);
      }
  }

  @Test(timeout = 100000)
  public void test4()  throws Throwable  {
      Util util0 = new Util();
  }
}
